routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('clients','ClientController');
Route::resource('credits','CreditController');

Route::get('/credits/viewCredit/{client_id}', 'CreditController@viewCredit')->name('viewCredit');
Route::get('/credits/addCredit/{client_id}', 'CreditController@addCredit')->name('addCredit');
Route::post('/credits/store/{client_id}', 'CreditController@store')->name('credits.store');
Route::get('/credits/edit/{id}/{client_id}', 'CreditController@edit')->name('credits.edit');
Route::put('/credits/update/{id}/{client_id}', 'CreditController@update')->name('credits.update');
Route::delete('/credits/destroy/{id}/{client_id}', 'CreditController@destroy')->name('credits.destroy');
Route::get('/clients/printAllCredit/{client_id}','ClientController@printAllCredit')->name('clients.printAllCredit');
// Route::get('printAllCredit', 'ClientController@printAllCredit')->name('clinets.printAllCredit');




// Route::get('/client/printAllCredit',[ 'as' => 'print.printAllCredit, 
// 'uses' => 'ClientController@printAllCredit']);
// <a href="{{route('client.printAllCredit')}}">Print PDF</a>

// Route::get('clients/printAllCredit/{credit->id}', function (Request $request, $credit) {
//     return $request->user()->downloadcredit($credit, [
//         'vendor' => 'Your Company',
//         'product' => 'Your Product',
//     ]);
// });






// Route::get('/viewCredit/{id}','CreditController@viewCredit')->name;

app/Client.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    //
    /**
     * The attributes that are mass assignable.
     *

     // migration ko field haru lyayera rakheko
     * @var array
     */
// credit ko filled client le access  gareko
    public function credits(){
         return $this->hasMany('App\Credit');
    }
    

    protected $fillable = [        
        'name',              
        'address',  
        'phonenumber',
        'balance'    
    ];
    

}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use DB;
use PDF;
use App\Client;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
            $clients = Client::all();        
            return view('clients.index', compact('clients'));    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([            
            'name'=>'required',                       
            'address'=>'required', 
            'phonenumber'=>'required'       
        ]);        
        $client = new Client([            
            'name' => $request->get('name'),                        
            'address' => $request->get('address'), 
            'phonenumber'=>$request->get('phonenumber')               
            ]);        
        $client->save(); 
        

        return redirect('/clients')->with('success', 'Client saved!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $client = Client::find($id);        
        return view('clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
       $request->validate([            
            'name'=>'required',                       
            'address'=>'required', 
            'phonenumber'=>'required'       
        ]);        
        $client = Client::find($id);        
        $client->name =  $request->get('name');             
        $client->address = $request->get('address');  
        $client->phonenumber = $request->get('phonenumber');          
        $client->save();        
        return redirect('/clients')->with('success', 'Client updated!');
    }
    public function destroy($id)
    {
        //
        $client = Client::find($id);        
        $client->delete();        
        return redirect('/clients')->with('success', 'Client deleted!');
 
   }
//    public function printAllCredit($id){
//      $credit=$this->get_credits();
//    $domPdfPath = base_path( 'vendor/dompdf/dompdf');
// \PhpOffice\PhpWord\Settings::setPdfRendererPath($domPdfPath);
// \PhpOffice\PhpWord\Settings::setPdfRendererName('DomPDF');
   
//   return view('dynamic_pdf')->with('credits',$credit);

   

//    }
   public function printAllCredit($client_id)
    {
        // 
    
     $pdf = \App::make('dompdf.wrapper');
     $pdf->loadHTML($this->convert_client_data_to_html($client_id));
     return $pdf->stream();
    }

    function convert_client_data_to_html($client_id)
    {
        $client = Client::find($client_id); 

     $credits= $client->credits;
   

     $output = '
   
     <h3 align="center">Client Data</h3>
     <table width="100%" style="border-collapse: collapse; border: 0px;">
     
     <tr>
     <th style="border: 1px solid; padding:12px;" width="20%">Name</th>
     <th style="border: 1px solid; padding:12px;" width="30%">Address</th>
     <th style="border: 1px solid; padding:12px;" width="30%">Balance</th>
     </tr>
     
     
     <tr>
     <td style="border: 1px solid; padding:12px;">'.$client->name.'</td>
    <td style="border: 1px solid; padding:12px;">'.$client->address.'</td>
    <td style="border: 1px solid; padding:12px;">'.$client->balance.'</td>
      
     </tr>
    
     
     
    

     
     
     <table class="table table-striped">  
     <table width="100%" style="border-collapse: collapse; border: 0px;"> 
      
     
      <tr>
      <th style="border: 1px solid; padding:12px;" width="20%">Date</th>
    <th style="border: 1px solid; padding:12px;" width="30%">Particular</th>
    <th style="border: 1px solid; padding:12px;" width="20%">Credit</th>
    <th style="border: 1px solid; padding:12px;" width="30%">Debit</th>
   
    
   </tr>
     ';  
     foreach($credits as $credit)
     {
      $output .= '
      <tr>
      <td style="border: 1px solid; padding:12px;">'.$credit->date.'</td>
       <td style="border: 1px solid; padding:12px;">'.$credit->particular.'</td>
       <td style="border: 1px solid; padding:12px;">'.$credit->credit.'</td>
       <td style="border: 1px solid; padding:12px;">'.$credit->debit.'</td>
     
      </tr>
      ';
      
     }
     $output .= '</table>';
     return $output;

    }
    

    

  }

resources/views/clients/create.blade.php
@extends('home')
@section('homecontent')
<div class="row"> 
    <div class="col-sm-8 offset-sm-2">    
        <h3 class="display-4">Add Client</h3>  
        <div>    
            @if ($errors->any())      
            <div class="alert alert-danger">        
                <ul>            
                @foreach ($errors->all() as $error)              
                <li>{{ $error }}</li>            
                @endforeach        
                </ul>      
            </div>
            <br />    
            @endif      
            <form method="post" action="{{ route('clients.store') }}">          
            @csrf          
            <div class="form-group">                  
                <label for="name">Name:</label>              
                <input type="text" class="form-control" name="name"/>          
            </div> 
            <div class="form-group">                  
                <label for="address">Address:</label>              
                <input type="text" class="form-control" name="address"/>          
            </div>  
            <div class="form-group">                  
                <label for="phonenumber">Phone Number:</label>              
                <input type="text" class="form-control" name="phonenumber"/>          
            </div> 
            <!-- <div class="form-group">                  
                <label for="balance">Balance:</label>              
                <input type="text" class="form-control" name="balance"/>          
            </div>                          -->
            <button type="submit" class="btn btn-success">Save</button>
            <a href="{{ route('clients.index') }}" class="btn btn-primary">Cancel</a>  
                
            </form>  
        </div>
    </div>
</div>
@endsection

resources/views/clients/edit.blade.php
@extends('home')
@section('homecontent')
<div class="row">    
    <div class="col-sm-8 offset-sm-2">        
        <h3 class="display-4">Update Client Record</h3>        
        @if ($errors->any())        
        <div class="alert alert-danger">            
            <ul>                
            @foreach ($errors->all() as $error)                
            <li>{{ $error }}</li>                
            @endforeach            
            </ul>        
        </div>        
        <br />         
        @endif        
        <form method="post" action="{{ route('clients.update', $client->id) }}">            
        @method('PATCH')             
        @csrf            
            <div class="form-group">                
                <label for="name">Name:</label>                
                <input type="text" class="form-control" name="name" value={{ $client->name }} />            
            </div>            
         <div class="form-group">                
                <label for="address">Address:</label>                
                <input type="text" class="form-control" name="address" value={{ $client->address }} />  
            </div>   
            <div class="form-group">                
                <label for="phonenumber">Phone Number:</label>                
                <input type="text" class="form-control" name="phonenumber" value={{ $client->phonenumber }} />  
            </div> 
            <div class="form-group">                
                <label for="balance">Balance:</label>                
                <input type="text" class="form-control" name="balance" value={{ $client->balance }} />  
                 </div>   

            <button type="submit" class="btn btn-success">Update</button>        
            <a href="{{ route('clients.index') }}" class="btn btn-primary">Cancel</a>                        
        </form>
    </div>
</div>
@endsection

resources/views/clients/index.blade.php
@extends('home')
@section('homecontent')

<div class="row">
    <div class="col-sm-12">    
        <h1 class="display-4">Clients</h1>   
        <a href="{{ route('clients.create') }}" class="btn btn-primary">Add</a>  
        <table class="table table-striped">    
            <thead>        
            <tr>          
                <td>ID</td>          
                <td>Name</td>
                <td>Address</td>  
                <td>Phone Number</td>
                 <td>Balance</td>

                <td colspan = 2>Actions</td>        
            </tr>    
            </thead>    
            <tbody>        
                @foreach($clients as $client)        
                    <tr>            
                        <td>{{$client->id}}</td>            
                        <td>{{$client->name}}</td>
                        <td>{{$client->address}}</td>
                          <td>{{$client->phonenumber}}</td>
                        <td>{{$client->balance}}</td>


                        <td>                                      
                            <a href="{{ route('clients.edit',$client->id)}}" class="btn btn-primary">Edit Client</a>
                                                                  

                        </td> 
                        <td>
                        <a href="{{ route('viewCredit',$client->id)}}" class="btn btn-primary">View Credit</a> 
                        </td> 
                        <td>  
                        <div target="_blank" >
                        <a href="{{ route('clients.printAllCredit',$client->id) }}"  class="btn btn-primary" >Print</a> 
                        </div>
                        </td>
                        <td>
                          <form action="{{ route('clients.destroy',$client->id )}}" method="post">                  
                                @csrf                  
                                @method('DELETE')                  
                                <button class="btn btn-danger" type="submit">Delete</button>                
                            </form>    
                                      
                        </td> 
                        
          
                        
                    </tr>        
                @endforeach    
            </tbody>  
        </table>
    <div>
</div>@endsection